/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account-settings'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as ApiDebugSendTestRouteImport } from './routes/api/debug/send-test'
import { Route as AuthenticatedContactsTagsRouteImport } from './routes/_authenticated/contacts.tags'
import { Route as AuthenticatedContactsImportRouteImport } from './routes/_authenticated/contacts.import'
import { Route as AuthenticatedContactsBulkRouteImport } from './routes/_authenticated/contacts.bulk'
import { Route as ApiPublicHooksProcessCampaignsRouteImport } from './routes/api/public/hooks/process-campaigns'
import { Route as ApiPublicHooksMetaWhatsappRouteImport } from './routes/api/public/hooks/meta-whatsapp'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const ApiDebugSendTestRoute = ApiDebugSendTestRouteImport.update({
  id: '/api/debug/send-test',
  path: '/api/debug/send-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsTagsRoute =
  AuthenticatedContactsTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const AuthenticatedContactsImportRoute =
  AuthenticatedContactsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const AuthenticatedContactsBulkRoute =
  AuthenticatedContactsBulkRouteImport.update({
    id: '/bulk',
    path: '/bulk',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const ApiPublicHooksProcessCampaignsRoute =
  ApiPublicHooksProcessCampaignsRouteImport.update({
    id: '/api/public/hooks/process-campaigns',
    path: '/api/public/hooks/process-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaWhatsappRoute =
  ApiPublicHooksMetaWhatsappRouteImport.update({
    id: '/api/public/hooks/meta-whatsapp',
    path: '/api/public/hooks/meta-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/contacts/bulk': typeof AuthenticatedContactsBulkRoute
  '/contacts/import': typeof AuthenticatedContactsImportRoute
  '/contacts/tags': typeof AuthenticatedContactsTagsRoute
  '/api/debug/send-test': typeof ApiDebugSendTestRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/api/public/hooks/meta-whatsapp': typeof ApiPublicHooksMetaWhatsappRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/contacts/bulk': typeof AuthenticatedContactsBulkRoute
  '/contacts/import': typeof AuthenticatedContactsImportRoute
  '/contacts/tags': typeof AuthenticatedContactsTagsRoute
  '/api/debug/send-test': typeof ApiDebugSendTestRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/api/public/hooks/meta-whatsapp': typeof ApiPublicHooksMetaWhatsappRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/contacts/bulk': typeof AuthenticatedContactsBulkRoute
  '/_authenticated/contacts/import': typeof AuthenticatedContactsImportRoute
  '/_authenticated/contacts/tags': typeof AuthenticatedContactsTagsRoute
  '/api/debug/send-test': typeof ApiDebugSendTestRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/api/public/hooks/meta-whatsapp': typeof ApiPublicHooksMetaWhatsappRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account-settings'
    | '/campaigns'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/help'
    | '/organization'
    | '/reports'
    | '/settings'
    | '/super-admin'
    | '/templates'
    | '/contacts/bulk'
    | '/contacts/import'
    | '/contacts/tags'
    | '/api/debug/send-test'
    | '/contacts/'
    | '/api/public/hooks/meta-whatsapp'
    | '/api/public/hooks/process-campaigns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account-settings'
    | '/campaigns'
    | '/conversations'
    | '/dashboard'
    | '/help'
    | '/organization'
    | '/reports'
    | '/settings'
    | '/super-admin'
    | '/templates'
    | '/contacts/bulk'
    | '/contacts/import'
    | '/contacts/tags'
    | '/api/debug/send-test'
    | '/contacts'
    | '/api/public/hooks/meta-whatsapp'
    | '/api/public/hooks/process-campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account-settings'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/organization'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/super-admin'
    | '/_authenticated/templates'
    | '/_authenticated/contacts/bulk'
    | '/_authenticated/contacts/import'
    | '/_authenticated/contacts/tags'
    | '/api/debug/send-test'
    | '/_authenticated/contacts/'
    | '/api/public/hooks/meta-whatsapp'
    | '/api/public/hooks/process-campaigns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiDebugSendTestRoute: typeof ApiDebugSendTestRoute
  ApiPublicHooksMetaWhatsappRoute: typeof ApiPublicHooksMetaWhatsappRoute
  ApiPublicHooksProcessCampaignsRoute: typeof ApiPublicHooksProcessCampaignsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings': {
      id: '/_authenticated/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/api/debug/send-test': {
      id: '/api/debug/send-test'
      path: '/api/debug/send-test'
      fullPath: '/api/debug/send-test'
      preLoaderRoute: typeof ApiDebugSendTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/tags': {
      id: '/_authenticated/contacts/tags'
      path: '/tags'
      fullPath: '/contacts/tags'
      preLoaderRoute: typeof AuthenticatedContactsTagsRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/contacts/import': {
      id: '/_authenticated/contacts/import'
      path: '/import'
      fullPath: '/contacts/import'
      preLoaderRoute: typeof AuthenticatedContactsImportRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/contacts/bulk': {
      id: '/_authenticated/contacts/bulk'
      path: '/bulk'
      fullPath: '/contacts/bulk'
      preLoaderRoute: typeof AuthenticatedContactsBulkRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/api/public/hooks/process-campaigns': {
      id: '/api/public/hooks/process-campaigns'
      path: '/api/public/hooks/process-campaigns'
      fullPath: '/api/public/hooks/process-campaigns'
      preLoaderRoute: typeof ApiPublicHooksProcessCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-whatsapp': {
      id: '/api/public/hooks/meta-whatsapp'
      path: '/api/public/hooks/meta-whatsapp'
      fullPath: '/api/public/hooks/meta-whatsapp'
      preLoaderRoute: typeof ApiPublicHooksMetaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsBulkRoute: typeof AuthenticatedContactsBulkRoute
  AuthenticatedContactsImportRoute: typeof AuthenticatedContactsImportRoute
  AuthenticatedContactsTagsRoute: typeof AuthenticatedContactsTagsRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsBulkRoute: AuthenticatedContactsBulkRoute,
  AuthenticatedContactsImportRoute: AuthenticatedContactsImportRoute,
  AuthenticatedContactsTagsRoute: AuthenticatedContactsTagsRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiDebugSendTestRoute: ApiDebugSendTestRoute,
  ApiPublicHooksMetaWhatsappRoute: ApiPublicHooksMetaWhatsappRoute,
  ApiPublicHooksProcessCampaignsRoute: ApiPublicHooksProcessCampaignsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
