// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

import WebSocket from "ws";

function envValue(...values: Array<string | undefined>) {
  for (const value of values) {
    const trimmed = value?.trim();
    if (trimmed) return trimmed;
  }
  return undefined;
}

type SupabaseClient = ReturnType<typeof createClient<Database>>;

function createSupabaseClient(): SupabaseClient {
  const SUPABASE_URL = envValue(
    typeof import.meta !== "undefined" ? import.meta.env?.VITE_SUPABASE_URL : undefined,
    typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined,
    typeof process !== "undefined" ? process.env?.VITE_SUPABASE_URL : undefined,
  );
  const SUPABASE_PUBLISHABLE_KEY = envValue(
    typeof import.meta !== "undefined" ? import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY : undefined,
    typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined,
    typeof process !== "undefined" ? process.env?.VITE_SUPABASE_PUBLISHABLE_KEY : undefined,
    typeof process !== "undefined" ? process.env?.SUPABASE_ANON_KEY : undefined,
    typeof process !== "undefined" ? process.env?.VITE_SUPABASE_ANON_KEY : undefined,
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure Supabase environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      transport: (typeof window === "undefined" ? WebSocket : undefined) as any,
    },
  });
}

let _supabase: SupabaseClient | undefined;

function getSupabaseClient(): SupabaseClient {
  if (!_supabase) _supabase = createSupabaseClient();
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase: SupabaseClient = new Proxy({} as SupabaseClient, {
  get(_, prop) {
    const client = getSupabaseClient();
    const value = Reflect.get(client, prop, client);
    return typeof value === "function" ? value.bind(client) : value;
  },
});
